{{- if or (and (eq .Values.vault.auth.type "token") .Values.vault.auth.token) (and (eq .Values.vault.auth.type "approle") (or .Values.vault.auth.roleId .Values.vault.auth.secretId)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-namespace-controller.fullname" . }}
  labels:
    {{- include "vault-namespace-controller.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and (eq .Values.vault.auth.type "token") .Values.vault.auth.token }}
  token: {{ .Values.vault.auth.token | b64enc }}
  {{- end }}
  {{- if and (eq .Values.vault.auth.type "approle") .Values.vault.auth.roleId }}
  role-id: {{ .Values.vault.auth.roleId | b64enc }}
  {{- end }}
  {{- if and (eq .Values.vault.auth.type "approle") .Values.vault.auth.secretId }}
  secret-id: {{ .Values.vault.auth.secretId | b64enc }}
  {{- end }}
{{- end }}
